// Derived from artifacts/admin-tracker/src/index.css — comic book palette
const colors = {
  light: {
    text:                 "#0D0D0D",
    tint:                 "#CC0000",
    background:           "#F5F1E8",
    foreground:           "#0D0D0D",
    card:                 "#FFFFFF",
    cardForeground:       "#0D0D0D",
    primary:              "#FFD700",
    primaryForeground:    "#1A1A1A",
    secondary:            "#1A1A1A",
    secondaryForeground:  "#FFFFFF",
    muted:                "#E5E5E5",
    mutedForeground:      "#666666",
    accent:               "#FFD700",
    accentForeground:     "#1A1A1A",
    destructive:          "#CC0000",
    destructiveForeground:"#FFFFFF",
    border:               "#1A1A1A",
    input:                "#CCCCCC",
    // semantic extras
    red:    "#CC0000",
    yellow: "#FFD700",
    purple: "#7C3AED",
    green:  "#059669",
    blue:   "#1D4ED8",
    orange: "#EA580C",
    amber:  "#D97706",
    gray:   "#6B7280",
  },
  dark: {
    text:                 "#F5F1E8",
    tint:                 "#FFD700",
    background:           "#111111",
    foreground:           "#F5F1E8",
    card:                 "#1C1C1C",
    cardForeground:       "#F5F1E8",
    primary:              "#FFD700",
    primaryForeground:    "#111111",
    secondary:            "#F0ECE0",
    secondaryForeground:  "#111111",
    muted:                "#2A2A2A",
    mutedForeground:      "#999999",
    accent:               "#FFD700",
    accentForeground:     "#111111",
    destructive:          "#FF3333",
    destructiveForeground:"#FFFFFF",
    border:               "#3A3A3A",
    input:                "#333333",
    red:    "#FF3333",
    yellow: "#FFD700",
    purple: "#A855F7",
    green:  "#10B981",
    blue:   "#3B82F6",
    orange: "#F97316",
    amber:  "#F59E0B",
    gray:   "#9CA3AF",
  },
  radius: 0,
};

export default colors;
